### ISSUE TITLE
Custom permalink URLs

### ISSUE THREAD

**Issue by leah** [mightylemon/mightylemon#14]
Allow for a specific url format (such as by date or just by id). Also allow for direct permalinks... ie: justinlilly.com/awesome/ will redirect you to a specific post.

**Comment by justinabrahms** [comment]
This is assuming the base site URL is justinlilly.com/. Can we make this assumption? Should base site url be a settings / blog level config? The implementation of this isn't terribly difficult, but knowing a little more will go a long way in helping.

**Comment by leah** [comment]
I'll file the url -> blog thing as a separate ticket. This really has more to do with individual post permalinks.

**Comment by justinabrahms** [comment]
Fixed.
