### ISSUE TITLE
Installation problems (syncdb fails)

### ISSUE THREAD

**Issue by restless** [mightylemon/mightylemon#24]
I've set up environment creating virtualenv and then installing requirements with pip. I've also set local settings to point to my postgresql db. The problem is that ./manage.py syndb fails. It returns a strange error statement: 

psycopg2.InternalError: BŁĄD:  current transaction is aborted, commands ignored until end of transaction block

I've some other envs with diffrent django projects (including pinax) but I've never ecountered the error like the one above.

I've found this: http://justinlilly.com/blog/2009/mar/13/psycopg2-internalerror/ but:
1. what has postgis to do with this blog?
2. I created db based on postgis template but it didn't change anything.

**Comment by scotu** [comment]
I can replicate the error on my ubuntu box, probably it comes from django-elsewhere as noted in this bug report but I haven't tried to debug it: http://github.com/leah/django-elsewhere/issues/#issue/1
It seams to happen only on postgresql (anyone on mysql can confirm this statement?).

**Comment by restless** [comment]
Indeed. I didn't notice that it is from django-elsewhere. It is quite easy to find a source of problem looking into models.py of django-elsewhere. It calls two functions when defining managers: SocialNetworkData() and InstantMessengerData() which try to access nonexisting tables (tables that are not yet created). This causes an error and leads to aborting a transaction.

**Comment by restless** [comment]
Ok, i've sumbitted a comment including a quick fix here: http://github.com/leah/django-elsewhere/issues/#issue/1 

Because this is elsewhere's issue I'm closing this issue here.
